version: '3'
services:
  api:
    build:
      dockerfile: ../Dockerfile.dev
      context: ./app-api
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./app-api:/app
    depends_on:
      - db
  auth:
    build:
      dockerfile: ../Dockerfile.dev
      context: ./app-auth
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./app-auth:/app
    depends_on:
      - db
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: if_carona_development
