version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_USER=admin
      - MYSQL_ROOT_HOST=172.20.0.3